version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # SonarCloud scan
      - sonarcloud/scan

      # Run tests
      - run:
          name: Run Tests
          command: |
            npm test
            npm install -g mocha
            mkdir ~/junit
            mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=~/junit/test-results.xml

      # Store test results
      - store_test_results:
          path: ~/junit

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud